server:
  port: ${PORT:0}
spring:
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url:  jdbc:mysql://localhost:3306/codeforsolution
    username: root
    password: mysql
    driver-class-name:  com.mysql.jdbc.Driver
  devtools:
    restart:
      enabled:  true

  client:
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/